"""add report and user fields

Revision ID: 9aa55ccf98a3
Revises: a988ea78eae4
Create Date: 2026-08-17 11:51:58.166538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa55ccf98a3'
down_revision: Union[str, Sequence[str], None] = 'a988ea78eae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('reports', sa.Column('arrests_made', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('animals_caught', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    op.drop_column('reports', 'animals_caught')
    op.drop_column('reports', 'arrests_made')
    op.alter_column('assignments', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
